# Site settings
title: Hendrig Sellik's home page
#baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://hsellik.github.io

# User settings
username: Hendrig Sellik
user_description: Hi, welcome to my home page. I am Hendrig, currently studying Computer Science at Delft University of Technology and making my Master Thesis at Adyen, Amsterdam. I am aiming to finish my studies during the Summer of 2020. Feel free to reach out to me through Linkedin!
email: blank
twitter_username: Hendrig Sellik
github_username:  hsellik


# Google-analytics
google-analytics:
  id: "UA-136769298-1"

plugins:
  - jekyll-sitemap

exclude: ['package.json', 'src' , 'node_modules', 'vendor']
