# Site settings
title: Hendrig Sellik's home page
#baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://hsellik.github.io

# User settings
username: Hendrig Sellik
user_description:
email: blank
twitter_username: Hendrig Sellik
github_username:  hsellik


# Google-analytics
google-analytics:
  id: "UA-136769298-1"

exclude: ['package.json', 'src' , 'node_modules', 'vendor']
