# Site settings
title: Hendrig Sellik
description: Hendrig Sellik's home page
#baseurl: "/particle" # the subpath of your site, e.g. /blog
#url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hendrig Sellik
user_description:
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  DontSeeSharp
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-136769298-1"

exclude: ['package.json', 'src' , 'node_modules']
