# Site settings
title: Hendrig Sellik's home page
#baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://hsellik.github.io

# User settings
username: Hendrig Sellik
user_description: Hi, welcome to my home page. I am Hendrig, currently working as a software engineer at RingIT (Tallinn, Estonia). I hold a B.Sc. degree in Informatics from TalTech (Estonia) and an M.Sc. degree in Computer Science from Delft University of Technology (Netherlands). <br /> <br />I specialize in software development, but I like everything related to technology and also have some experience in data science / machine learning. Feel free to reach out to me through Linkedin!
email: blank
twitter_username: Hendrig Sellik
github_username:  hsellik


# Google-analytics
google-analytics:
  id: "UA-136769298-1"

plugins:
  - jekyll-sitemap

exclude: ['package.json', 'src' , 'node_modules', 'vendor']
